spring:
  application:
    name: BookStorage
  banner:
    charset: UTF-8
    location: banner
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: never
      data-locations: classpath:sql_data/*
  datasource:
    username: dora
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/blog
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    defer-datasource-initialization: true
