INSERT INTO roles (name)
VALUES ('ADMIN'),
       ('EDITOR'),
       ('VIEWER'),
       ('AUTHOR'),
       ('MODERATOR'),
       ('CONTRIBUTOR'),
       ('SUBSCRIBER'),
       ('GUEST'),
       ('REVIEWER'),
       ('ANALYST'),
       ('MANAGER'),
       ('DEVELOPER'),
       ('DESIGNER'),
       ('TESTER'),
       ('PRODUCT_OWNER'),
       ('SCRUM_MASTER'),
       ('CEO'),
       ('CTO'),
       ('HR'),
       ('INTERN');