INSERT INTO blogs (name, manager_id)
VALUES ('Tech Trends', 1),
       ('AI Revolution', 2),
       ('Cloud Computing', 3),
       ('Cybersecurity Insights', 4),
       ('Gadget Reviews', 5),
       ('Web Development', 6),
       ('Mobile Apps', 7),
       ('Game Development', 8),
       ('Blockchain News', 9),
       ('Startup Success', 10),
       ('Big Data & Analytics', 11),
       ('AR/VR Updates', 12),
       ('Quantum Computing', 13),
       ('IoT and Smart Devices', 14),
       ('Tech Policy & Law', 15),
       ('Programming Tips', 16),
       ('DevOps & Automation', 17),
       ('AI Ethics', 18),
       ('E-commerce Trends', 19),
       ('Future of Tech', 20);
