INSERT INTO articles (title, author_id, blog_id)
VALUES ('Introduction to AI', 1, 1),
       ('Deep Learning Basics', 2, 2),
       ('Cloud vs On-Premise', 3, 3),
       ('Top 10 Cyber Threats', 4, 4),
       ('Best Smartphones of 2025', 5, 5),
       ('CSS Grid vs Flexbox', 6, 6),
       ('Flutter vs React Native', 7, 7),
       ('Unity vs Unreal Engine', 8, 8),
       ('How Blockchain Works', 9, 9),
       ('Scaling Your Startup', 10, 10),
       ('Data Science for Beginners', 11, 11),
       ('How AR is Changing Retail', 12, 12),
       ('Quantum Computers Explained', 13, 13),
       ('Smart Homes of the Future', 14, 14),
       ('Tech Regulations & Privacy', 15, 15),
       ('Best Coding Practices', 16, 16),
       ('CI/CD for Beginners', 17, 17),
       ('AI Bias and Ethics', 18, 18),
       ('How AI is Shaping E-commerce', 19, 19),
       ('What’s Next in Tech?', 20, 20);